services:

  # ---------------------------
  # Elasticsearch single-node per DEV (RAM bassa)
  # ---------------------------
  es01:
    container_name: ragflow-es-01
    image: elasticsearch:${STACK_VERSION}
    env_file: .env
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT:-9200}:9200"
    environment:
      - node.name=es01
      - cluster.name=ragflow-cluster
      - network.host=0.0.0.0
      - discovery.type=single-node   # Single-node per DEV
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m    # RAM bassa per DEV
      - xpack.security.enabled=false
      - TZ=${TIMEZONE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    healthcheck:
      test:
        - "CMD-SHELL"
        - >
          curl -fsSL localhost:9200/_cluster/health?pretty |
          grep '"status"\s*:\s*"green"'
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - ragflow
    restart: on-failure

  # ---------------------------
  # Infinity (SOLO SE ATTTIVI IL PROFILO infinity)
  # ---------------------------
  infinity:
    container_name: ragflow-infinity
    profiles:
      - infinity
    image: infiniflow/infinity:v0.6.0-dev3
    volumes:
      - infinity_data:/var/infinity
      - ./infinity_conf.toml:/infinity_conf.toml
    command: ["-f", "/infinity_conf.toml"]
    ports:
      - ${INFINITY_THRIFT_PORT:-23817}:23817
      - ${INFINITY_HTTP_PORT:-23820}:23820
      - 15432:5432    # <--- Port HOST 15432, nessun conflitto con postgres!
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      nofile:
        soft: 500000
        hard: 500000
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "curl", "http://localhost:23820/admin/node/current"]
      interval: 10s
      timeout: 10s
      retries: 120
    restart: on-failure

  # ---------------------------
  # MYSQL 8
  # ---------------------------
  mysql:
    image: mysql:8.0.39
    container_name: ragflow-mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
      --binlog_expire_logs_seconds=604800
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure

  # ---------------------------
  # MinIO
  # ---------------------------
  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: ragflow-minio
    command: server --console-address ":9001" /data
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - minio_data:/data
    networks:
      - ragflow
    restart: on-failure

  # ---------------------------
  # Redis
  # ---------------------------
  redis:
    image: valkey/valkey:8
    container_name: ragflow-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
    env_file: .env
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/data
    networks:
      - ragflow
    restart: on-failure

  # ---------------------------
  # Backend OAuth (esempio)
  # ---------------------------
  backendoauth:
    container_name: ragflow-backend-oauth
    build:
      context: ../web/src/pages/login-page
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TZ=${TIMEZONE}
    networks:
      - ragflow
    restart: on-failure  

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  infinity_data:
    driver: local
  mysql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  ragflow:
    driver: bridge